// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbUXTJJxYCLw5g91O3BbRd0TDB6L8qlN8',
    appId: '1:615852851202:android:9ffd535941320515c0e71b',
    messagingSenderId: '615852851202',
    projectId: 'rice-disease-recognition-app',
    storageBucket: 'rice-disease-recognition-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi5gtKRSsgZove4eKlT7fDqqNdS2BWvM4',
    appId: '1:615852851202:ios:34bee32362b02dafc0e71b',
    messagingSenderId: '615852851202',
    projectId: 'rice-disease-recognition-app',
    storageBucket: 'rice-disease-recognition-app.firebasestorage.app',
    iosBundleId: 'com.rice.scanapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDtFAZRVJadES0xwy9wa3dFLz50DXPVE',
    appId: '1:615852851202:web:bb06aa8df2fcbb2bc0e71b',
    messagingSenderId: '615852851202',
    projectId: 'rice-disease-recognition-app',
    authDomain: 'rice-disease-recognition-app.firebaseapp.com',
    storageBucket: 'rice-disease-recognition-app.firebasestorage.app',
  );

}